# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'AutoCepticons' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AutoCepticons

  target 'AutoCepticonsTests' do
    inherit! :search_paths
    pod "Quick"
    pod "Nimble-Snapshots"
  end

end
